### PR TITLE
Refactoring and amends - various Trello cards

### PR DESCRIPTION
**Pull request by jimleeder123**
This PR is for the 5 refactoring cards recently created. These include...

- SC landing page - 1 button for auth user
- Auth prefix added to sign out URLs
- Outputs HTTP naming refactored
- Outputs request path changed
- Notifications directory structure - the detailed and summary notifications are now in a SC folder

### CODE REVIEW

**Comment by jimleeder123** [comment]
[Space calculator landing page buttons](https://trello.com/c/1cQDYOZv/88-space-calculator-landing-page-buttons)

**Comment by jimleeder123** [comment]
[Auth prefix missing on sign out URLs](https://trello.com/c/3isCifvf/90-auth-prefix-missing-on-sign-out-urls)

**Comment by jimleeder123** [comment]
[Refactor outputs HTTP naming](https://trello.com/c/5q7ngau0/89-refactor-outputs-http-naming)

**Comment by jimleeder123** [comment]
[Refactor outputs HTTP request path](https://trello.com/c/kSZqKAiW/91-refactor-outputs-http-request-path)

**Comment by jimleeder123** [comment]
[Refactor notifications structure](https://trello.com/c/gDlosMiA/92-refactor-notifications-structure)

**Review by gbuckingham89 — APPROVED** [review]
Perfect! ✅

**Pull request merged**
