### PR TITLE
Space Calculator Landing Page

### PR DESCRIPTION
**Pull request by jimleeder123**
We already had the controller and route set up from the previous PR / card so that isn't included here. There is now test content on the view extending the skeleton. 

I've also set up a test for it. I've based the folder structure for the tests on a mixture of what is done for Tower and what has been done for the widgets controllers.

### CODE REVIEW

**Comment by jimleeder123** [comment]
[Space calculator landing page: HTTP flow](https://trello.com/c/quUMujWU/32-space-calculator-landing-page-http-flow)

**Review by gbuckingham89 — CHANGES_REQUESTED** [review]
Great work starting to add some tests.

Generally we try to mirror the path to controllers in the tests directory - so as we don't have a `widgets` sub directory there _(and rightly so, probably overkill for a project hits small)_ can we remove it from the tests structure?

Also, it should be named `GetIndexTest` - so it mirrors the name of the controller methods.

I like the thinking, but not sure how useful the `assertSessionHasNoErrors()` is, as the index route will never be throwing an errors?

We could also maybe add an assertion that we're showing the correct view with `->assertViewIs('path.to.view;)`

**Comment by jimleeder123** [comment]
> Great work starting to add some tests.
> 
> Generally we try to mirror the path to controllers in the tests directory - so as we don't have a `widgets` sub directory there _(and rightly so, probably overkill for a project hits small)_ can we remove it from the tests structure?
> 
> Also, it should be named `GetIndexTest` - so it mirrors the name of the controller methods.
> 
> I like the thinking, but not sure how useful the `assertSessionHasNoErrors()` is, as the index route will never be throwing an errors?
> 
> We could also maybe add an assertion that we're showing the correct view with `->assertViewIs('path.to.view;)`

Thanks, I've applied these changes

**Review by gbuckingham89 — APPROVED** [review]
Perfect 👌

I think I went overboard in RSO with some of the content assertions - the tests are quire "brittle" - "the fluffy" text on pages is likely to change, so tests shouldn't fail because of that. We don't want tests to be too onerous / high maintenance!

**Pull request merged**
